# Generated by Django 4.1.6 on 2023-02-16 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal_type', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=6)),
                ('lifeStatus', models.CharField(choices=[('ALIVE', 'ALIVE'), ('DEAD', 'DEAD')], default='ALIVE', max_length=5)),
                ('chippingDateTime', models.DateTimeField(auto_now_add=True)),
                ('deathDateTime', models.DateTimeField(default=None, null=True)),
                ('animalTypes', models.ManyToManyField(to='animal_type.animaltype')),
                ('chipperId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chippingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
