# Generated by Django 4.1.6 on 2023-03-03 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animal_chipperid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-09)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-09)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-09)]),
        ),
    ]
